config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'

  get 'dashboard/index'
  get 'activities/index'
  get 'profile/:id', to: 'profile#show', as: :profile

  get 'pricing', to: 'pages#pricing', as: :pricing

  resources :projects do
    resources :tasks do
      member do
        patch 'remove_team_member'
      end
    end

    member do
      get 'team_members'
      get 'reports'
      get 'project_report'
    end
  end

  resources :team_members

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_for :team_members, controllers: {
    sessions: 'project_members/sessions'
  }, path: 'project_members'
end

app/models/task.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: tasks
#
#  id          :uuid             not null, primary key
#  project_id  :uuid             not null
#  name        :string
#  description :text
#  end_date    :datetime
#  start_date  :datetime
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  account_id  :uuid             not null
#  status      :string
#
class Task < ApplicationRecord
  acts_as_tenant(:account)
  belongs_to :project

  has_and_belongs_to_many :team_members

  # Public activity tracking
  include PublicActivity::Model
  tracked owner: proc { |controller, _model| controller.current_tenant }

  has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy

  # validations
  validates :name, :description, :status, presence: true

  # time validations
  validates :start_date,
            comparison: { less_than: :end_date, message: "for the task can't be after the task's end date" }
  validates :end_date,
            comparison: { greater_than: :start_date, message: "for the task can't be before the task's start date" }

  TASK_STATUS = [
    'Not Started',
    'In progress',
    'Complete'
  ].freeze

  def to_s
    name
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  set_current_tenant_through_filter
  before_action :set_current_account
  layout 'dashboard'
  devise_group :project_member, contains: %i[user team_member]

  before_action :authenticate_project_member!

  # GET /tasks/1 or /tasks/1.json
  def show
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  # GET /tasks/new
  def new
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build

    # @available_team_members = []
    # TeamMember.all.each do |team_member|
    #   if team_member.tasks.count < 5
    #     @available_team_members << team_member
    #   end
    # end
    # # byebug
    # @available_team_members
  end

  # GET /tasks/1/edit
  def edit
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    # @available_team_members = TeamMemberTaskManager.new.team_member_task_manager(TeamMember.all)
    # @available_team_members = []
    # TeamMember.all.each do |team_member|
    #   if team_member.tasks.count < 5
    #     @available_team_members << team_member
    #   end
    # end
    # # byebug
    # @available_team_members
  end

  # POST /tasks or /tasks.json
  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_path(@project), notice: 'Task was successfully created.' }

      else
        flash.now[:alert] = 'Task has not been created'
        format.html { render :new, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.' }

      else
        flash.now[:alert] = 'Task has not been updated'
        format.html { render :edit, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    @task.destroy

    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_team_member
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])

    respond_to do |format|
      @task.team_members.delete(params[:team_member_id])
      format.html do
        redirect_to project_task_path(@project, @task),
                    notice: 'Team Member has been successfully removed from the task'
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  def set_current_account
    return unless current_user.present?

    current_account = current_user.account
    ActsAsTenant.current_tenant = current_account
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :description, :end_date, :start_date, :status, team_member_ids: [])
  end
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
end

app/views/tasks/_form.html.erb
<div class="card mb-3">
  <div class="card-header">
    <div class="row flex-between-end">
      <div class="col-auto align-self-center">
        <h5 class="mb-0" data-anchor="data-anchor">Task Details</h5>
      </div>
    </div>
  </div>
  <div class="card-body bg-light">
    <%= form_with(model: [project, task]) do |form| %>
      <% if task.errors.any? %>
        <div style="color: red">
          <h6 class="fw-normal text-700"><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h6>

          <ul>
            <% task.errors.each do |error| %>
              <li><span class="badge bg-danger"><%= error.full_message %></span></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row gx-2">
        <div class="col-12 mb-3">
          <%= form.label :name, class: "form-label" %>
          <%= form.text_field :name, class: "form-control" %>
        </div>

        <div class="col-12 mb-3">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_area :description, class: "form-control" %>
        </div>

        <div class="col-6 mb-3">
          <%= form.label :start_date, class: "form-label" %>
          <%= form.datetime_field :start_date, class: "form-control" %>
        </div>

        <div class="col-6 mb-3">
          <%= form.label :end_date, class: "form-label" %>
          <%= form.datetime_field :end_date, class: "form-control" %>
        </div>

        <div class="col-12 mb-3" data-controller="team-member">
          <%= form.label :task_status, class: "form-label", id: "task-status" %>
          <%= form.select :status, 
                          options_for_select(Task::TASK_STATUS, selected: task.status),
                          { prompt: "Select task status" },
                          class: "form-select"
                          %>
        </div>

        <div class="col-12 mb-3">
          <%= form.label :assign_team_members_to_task, class: "form-label" %>&nbsp;
          
          <span><%= link_to "Add new team member" , new_team_member_path, class: "btn btn-primary btn-sm me-1 mb-1"%></span>
          
         
          <%= form.select :team_member_ids, 
                          options_from_collection_for_select(TeamMember.all,:id, :full_name, selected: task.team_member_ids),
                          { include_blank: false }, 
                          id: "multiple",
                          multiple: "multiple",
                          size: 1 %>
        
        </div>
      </div>



      <div>
       
        <%= form.submit class: "btn btn-primary"  %>
        
        <% if task.persisted? %>
          <%= link_to "Cancel", project_path(@project), class: "btn btn-secondary me-1" %> 
        <%else%>
          <%= link_to "Back to project", project_path(@project), class: "btn btn-secondary me-1" %>
        <%end%>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="card-body py-0">
  <div class="table-responsive scrollbar">
    <table class="table table-dashboard mb-0 fs--1">
      <tr>
        <td class="align-middle ps-0 text-nowrap">
          <div class="d-flex position-relative align-items-center">

            <div class="flex-1">
              
                <%= link_to project_task_path(@project, task) ,class: "stretched-link" do %>
                  <p class="text-primary mb-0">
                    <%= truncate(task.name, length: 35, omission:"...") %> Task
                  </p>
                <%end%>
                <small class="fs--1 mb-0">
                  <span class="text-black">Task Status:</span>&nbsp;<span class="badge rounded-pill badge-soft-info"><%= task.status %></span>
                </small><br>
                <small class="fs--1 mb-0">
                  <span class="text-black">Total Team Members:</span> <%= task.team_members.count %>
                </small><br>
                <small class="fs--1 mb-0">
                  Start Date: <%= task.start_date.strftime("%d %b %Y at %H:%M %p") %>
                </small><br>

                <small class="fs--1 mb-0">
                  End Date: <%= task.end_date.strftime("%d %b %Y at %H:%M %p") %>
                </small><br>
              
                <small class="mb-0">
                      
                  Created | Edited by 
                  <span class="text-700"><%= task.project.user.full_name %></span>
  
                </small>
              
            </div>
          </div>
        </td>
        
        <td class="align-middle px-1 text-end text-nowrap" style="width:1%;">
          <%= link_to  "View", project_task_path(@project, task), class: "btn btn-success btn-sm me-1" %>
        </td>

      </tr>

    </table>
  </div>
</div>

app/views/tasks/_team_member_preview.html.erb
<% unless team_member.id == nil %>
  <div class="col-6 col-md-4 col-lg-3 col-xxl-2 mb-1">
    <div class="bg-white dark__bg-1100 p-3 h-100">
      <%= link_to image_tag("team/man.png", class: "img-thumbnail img-fluid rounded-circle mb-3 shadow-sm", alt: "", width: "100"), team_member %>
      <h6 class="mb-1">
        <%= team_member.first_name %>
      </h6>
      <%= button_to remove_team_member_project_task_path(@project,@task), params: {team_member_id: team_member.id }, method: :patch, class: "btn btn-outline-danger btn-sm fs--2" do  %>
        Remove from task <span class="fas fa-trash ms-1" data-fa-transform="shrink-3"></span>
      <%end%>
    </div>
  </div>
<%end%>

app/views/tasks/edit.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>

      <%= render "layouts/flash" %>
      <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(<%= asset_path "illustrations/corner-4.png" %>);">
        </div>
       

        <div class="card-body position-relative">
          <div class="row">
            <div class="col-lg-8">
              <h3>Edit Task</h3>
            </div>
          </div>
        </div>
      </div>

      <%= render "form", project: @project, task: @task %>

    

      
    </div>
    
  </div>
</main>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>

<%= link_to "New task", new_task_path %>

app/views/tasks/new.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>

      <%= render "layouts/flash" %>
      <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(<%= asset_path "illustrations/corner-4.png" %>);">
        </div>
      

        <div class="card-body position-relative">
          <div class="row">
            <div class="col-lg-8">
              <h3>New Task</h3>
            </div>
          </div>
        </div>
      </div>

      <%= render "form", project: @project, task: @task %>


      
    </div>
    
  </div>
</main>

app/views/tasks/show.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>

      <%= render "layouts/flash" %>

      
      <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(<%= asset_path "illustrations/corner-4.png" %>);">
        </div>
        

        <div class="card-body position-relative">
          <div class="row">
            <div class="col-lg-8">
              <h3>Task for <%= @project.project_name %></h3>
              <span class="badge badge-soft-info"><%= @task.status %></span>
              <div class="mt-2"><%= link_to "Back to Project", project_path(@project), class: "btn btn-falcon-info btn-sm px-3 " %></div>
            </div>
          </div>
        </div>
      </div>


      <div class="col-12">
        <div class="col-12 mb-2">
          <div class="card mb-3">  
            <div class="card-body">
              <h4 class="fw-normal text-700"><%= @task.name %></h4>
              <p class="card-text mb-1"><span class="fs--1 text-black">Start Date: </span>  <%= @task.start_date.strftime("%d %b %Y at %H:%M %p")  %></p>
              <p class="card-text mb-1"><span class="fs--1 text-black">End Date: </span>  <%= @task.end_date.strftime("%d %b %Y at %H:%M %p") %></p>
              <p class="card-text mb-1"><span class="fs--1 text-black">Team Members: </span>  <%= @task.team_members.count %></p>

              <br>

              <h6 class="text-700">Task Description</h6>
              <p class="card-text"><%= @task.description %></p>
                <%= link_to "Edit", 
                  edit_project_task_path(@project, @task),
                  class: "btn btn-primary btn-sm me-1 mb-1",
                  data: { turbo: false }
                    %>
                <%= link_to "Destroy", project_task_path(@project,@task), class: "btn btn-danger btn-sm me-1 mb-1", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    
            </div>
          </div>

          <div class="card">
            <div class="card-header d-flex justify-content-between">
              <h5 class="mb-0 text-black fw-normal">Team Members for <%= @task.name %></h5>
              <% if user_signed_in? %>
              <%= link_to edit_project_task_path(@project, @task), class: "btn btn-falcon-default btn-sm", data: {turbo: false } do %>
                <span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span>
                <span class="d-none d-sm-inline-block ms-1">Add New Team Members</span>
              <%end%>
              <%end%>
               
            </div>
            <div class="card-body bg-light px-1 py-0">
              <div class="row g-0 text-center fs--1">
                <% @task.team_members.each do |team_member| %>
                  <%= render partial: "tasks/team_member_preview", locals: {team_member: team_member} %>
                <%end%>
              </div>
              
              
            </div>


          </div>
        </div>
      </div>



    </div>
    
  </div>
</main>