config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'

  get 'dashboard/index'
  get 'activities/index'
  get 'profile/:id', to: 'profile#show', as: :profile

  get 'pricing', to: 'pages#pricing', as: :pricing

  resources :projects do
    resources :tasks do
      member do
        patch 'remove_team_member'
      end
    end

    member do
      get 'team_members'
      get 'reports'
      get 'project_report'
    end
  end

  resources :team_members

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_for :team_members, controllers: {
    sessions: 'project_members/sessions'
  }, path: 'project_members'
end

app/models/team_member.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: team_members
#
#  id                     :uuid             not null, primary key
#  first_name             :string           not null
#  last_name              :string           not null
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  account_id             :uuid             not null
#  terms_agreement        :boolean          default(FALSE), not null
#
class TeamMember < ApplicationRecord
  acts_as_tenant(:account)

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :lockable, :confirmable

  # associations
  has_and_belongs_to_many :tasks

  # Public activity tracking
  include PublicActivity::Model
  tracked owner: proc { |controller, _model| controller.current_tenant }

  has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy

  # validations
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates_acceptance_of :terms_agreement, allow_nil: false, on: :create

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/team_members_controller.rb
# frozen_string_literal: true

class TeamMembersController < ApplicationController
  set_current_tenant_through_filter
  before_action :set_current_account
  layout 'dashboard'

  devise_group :project_member, contains: %i[user team_member]

  before_action :authenticate_project_member!

  def index
    @pagy, @team_members = pagy(TeamMember.order(created_at: :desc), items: 10)
  end

  def new
    @team_member = TeamMember.new
  end

  def show
    @team_member = TeamMember.find(params[:id])
  end

  def edit
    @team_member = TeamMember.find(params[:id])
  end

  def destroy
    @team_member = TeamMember.find(params[:id])

    @team_member.destroy

    flash[:notice] = 'Team Member has been deleted'

    redirect_to team_members_path
  end

  def update
    params[:team_member].delete(:password) if params[:team_member][:password].blank?

    @team_member = TeamMember.find(params[:id])

    respond_to do |format|
      if @team_member.update(team_member_params)
        format.html { redirect_to team_member_path(@team_member), notice: 'Team member was successfully updated' }
      else
        flash.now[:alert] = 'Team member has not been updated'
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def create
    @team_member = TeamMember.new(team_member_params)
    respond_to do |format|
      if @team_member.save

        format.html { redirect_to team_members_path, notice: 'Team Member was successfully created' }

      else
        flash.now[:alert] = 'Team member has not been created'
        format.html { render :new, status: :unprocessable_entity }

      end
    end
  end

  private

  def team_member_params
    params.require(:team_member).permit(:first_name, :last_name, :email, :password, :terms_agreement, role_ids: [])
  end

  def set_current_account
    return unless current_user.present?

    current_account = current_user.account
    ActsAsTenant.current_tenant = current_account
  end
end

app/views/team_members/_form.html.erb
<div class="card mb-3">
  <div class="card-header">
    <div class="row flex-between-end">
      <div class="col-auto align-self-center">
        <h5 class="mb-0" data-anchor="data-anchor">Team Member Details</h5>
      </div>
    </div>
  </div>

  <div class="card-body bg-light">
    <%= form_with(model: team_member, autocomplete: "off", data: { turbo: false }) do |form| %>
      <% if team_member.errors.any? %>
        <div>
          <h6 class="fw-normal text-700"><%= pluralize(team_member.errors.count, "error") %> prohibited this team_member from being saved:</h6>

          <ul>
            <% team_member.errors.each do |error| %>
              <li><span class="badge bg-danger"><%= error.full_message %></span></li>
            <% end %>
          </ul>
        </div>
      <% end %>


      <div class="row gx-2">
        <div class="col-6 mb-3">
          <%= form.label :first_name, class: "form-label" %>
          <%= form.text_field :first_name, class: "form-control" %>
        </div>

        <div class="col-6 mb-3">
          <%= form.label :last_name, class: "form-label" %>
          <%= form.text_field :last_name, class: "form-control" %>
        </div>

        <div class="col-12 mb-3">
          <%= form.label :email, class: "form-label" %>
          <%= form.email_field :email, class: "form-control", autocomplete: "false"  %>
        </div>

        <div class="col-12 mb-3">
          <%= form.label :password, class: "form-label" %>
          <%= form.password_field :password, class: "form-control" %>
        </div>




        <div class="form-check">
          <%= form.check_box :terms_agreement, class: "form-check-input", id: "team-member-checkbox" %>
          <%= form.label :terms_agreement, ("I accept the #{ link_to "terms", "#", target: "_blank"} and #{ link_to "privacy policy", "#", target: "_blank"}").html_safe, class: "form-label" %>
        </div> 

      </div>

      <div>
        <%= form.submit class: "btn btn-primary" %>
        <% if team_member.persisted? %>
          <%= link_to "Cancel", team_member_path(@team_member), class: "btn btn-secondary me-1" %>
        <%else%>
          <%= link_to "Back to team members", team_members_path, class: "btn btn-secondary me-1"%>
        <%end%>
      </div>
    <% end %>
  </div>
</div>

app/views/team_members/_list_of_team_members.html.erb
<div class="card">
  <div class="card-header">
    <div class="row flex-between-center">
      <div class="col-4 col-sm-auto d-flex align-items-center pe-0">
        <h5 class="fs-0 mb-0 text-nowrap py-2 py-xl-0">Team Members</h5>
      </div>
      <div class="col-8 col-sm-auto text-end ps-2">
        <div id="table-customers-replace-element">
        
          <%= link_to new_team_member_path, class: "btn btn-falcon-default btn-sm" do %>
            <span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span>
            <span class="d-none d-sm-inline-block ms-1">New</span>
          <%end%>


        </div>
      </div>
    </div>
  </div>
  <div class="card-body bg-light px-1 py-0">
    <div class="row g-0 text-center fs--1">
      <% @team_members.each do |team_member| %>
        <%= render partial: "team_member_preview", locals: {team_member: team_member} %>
      <%end%>
    </div>
    
    
  </div>

  <%= render "team_members/pagination" %>

app/views/team_members/_pagination.html.erb
<% unless @team_members.empty? %>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </ul>
</nav>
<%end%>

app/views/team_members/_task.html.erb
<div class="card-body py-0">
  <div class="table-responsive scrollbar">
    <table class="table table-dashboard mb-0 fs--1">
      <tr>
        <td class="align-middle ps-0 text-nowrap">
          <div class="d-flex position-relative align-items-center">

            <div class="flex-1">
              
              <%= link_to project_task_path(@project, task) ,class: "stretched-link" do %>
                <p class="text-primary mb-0">
                  <%= truncate(task.name, length: 35, omission:"...") %> Task
                </p>
              <%end%>
                <small class="fs--1 mb-0">
                  <span class="text-black">Total Team Members:</span> <%= task.team_members.count %>
                </small><br>
                <small class="fs--1 mb-0">
                  Start Date: <%= task.start_date.strftime("%d %b %Y at %H:%M %p") %>
                </small><br>

                <small class="fs--1 mb-0">
                  End Date: <%= task.end_date.strftime("%d %b %Y at %H:%M %p") %>
                </small><br>
              
                <small class="mb-0">
                      
                  Created | Edited by 
                  <span class="text-700"><%= task.project.user.full_name %></span>
  
                </small>
              
            </div>
          </div>
        </td>
        
        <td class="align-middle px-1 text-end text-nowrap" style="width:1%;">
          <%= link_to  "View", project_task_path(@project, task), class: "btn btn-success btn-sm me-1" %>
        </td>

      </tr>

    </table>
  </div>
</div>


app/views/team_members/_team_member.html.erb
  <h6 class="fs-0 mb-0">
    <%= @team_member.full_name %>
    <span data-bs-toggle="tooltip" data-bs-placement="top" title="Verified">
      <small class="fa fa-check-circle text-primary" data-fa-transform="shrink-4 down-2"></small>
    </span>
  </h6>
  <div class="collapse show" id="client-info">
    <p class="mb-0"><%= @team_member.email %></p>
    <p class="mb-1"><%= @team_member.created_at %></p>

    <div class="border-dashed-bottom my-3"></div>
    <% if user_signed_in? %>
    <small class="text-500">Actions</small>
    <div>
      <%= link_to "Edit",edit_team_member_path(@team_member),class: "btn btn-primary btn-sm me-1 mb-1", data: { turbo: false } %>
      <%= link_to "Destroy", team_member_path(@team_member), class: "btn btn-danger btn-sm me-1 mb-1", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </div>
    <%end%>
  </div>

app/views/team_members/_team_member_preview.html.erb
<% unless team_member.id == nil %>
  <div class="col-6 col-md-4 col-lg-3 col-xxl-2 mb-1">
    <div class="bg-white dark__bg-1100 p-3 h-100">
      <%= link_to image_tag("team/man.png", class: "img-thumbnail img-fluid rounded-circle mb-3 shadow-sm", alt: "", width: "100"), team_member %>
      <h6 class="mb-1">
        <%= link_to team_member.first_name, team_member %>
      </h6>
      

    </div>
  </div>
<%end%>

app/views/team_members/edit.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>

      <%= render "layouts/flash" %>
      <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(<%= asset_path "illustrations/corner-4.png" %>);">
        </div>
       

        <div class="card-body position-relative">
          <div class="row">
            <div class="col-lg-8">
              <h3>Edit Team Member</h3>
            </div>
          </div>
        </div>
      </div>

      <%= render "form", team_member: @team_member %>


      
    </div>
    
  </div>
</main>

app/views/team_members/index.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>

      <%= render "layouts/flash" %>
      

      <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(<%= asset_path "illustrations/corner-4.png" %>);">
        </div>
        

        <div class="card-body position-relative">
          <div class="row">
            <div class="col-lg-8">
            <% if team_member_signed_in? %>
              <h3><%= current_team_member.account.user.first_name %>'s team  </h3>
            <%else%>
              <h3><%= current_user.first_name %>'s team </h3>
            <%end%>
              <p class="mb-0">List of all Team Members</p>
            </div>
          </div>
        </div>
      </div>


      <%= render "team_members/list_of_team_members" %>

     

      
    </div>
    
  </div>

</main>

app/views/team_members/new.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>


      <%= render "layouts/flash" %>
      
      <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(<%= asset_path "illustrations/corner-4.png" %>);">
        </div>
       

        <div class="card-body position-relative">
          <div class="row">
            <div class="col-lg-8">
              <h3>New Team Member</h3>
            </div>
          </div>
        </div>
      </div>

      <%= render "form", team_member: @team_member %>

    

      
    </div>
    
  </div>
</main>

app/views/team_members/show.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>

      <%= render "layouts/flash" %>

      <div class="card mb-3">
        <div class="card-header bg-progress-gradient position-relative min-vh-25 mb-7">
          
         

          <div class="avatar avatar-5xl avatar-profile">
            <%= image_tag "team/man.png", class: "rounded-circle img-thumbnail shadow-sm", width: "200", alt: "" %>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-8">
              <h4 class="mb-1"><%= @team_member.full_name %>
                <span data-bs-toggle="tooltip" data-bs-placement="right" title="Verified">
                  <small class="fa fa-check-circle text-primary" data-fa-transform="shrink-4 down-2"></small>
                </span>
              </h4>
              <h5 class=" fw-normal">
                <small>created by <%= @team_member.account.user.full_name %></span></small>                
              </h5>

              <p class="text-500"><small>created on: <%= @team_member.created_at.strftime("%a, %d %B %Y %H:%M ") %></small> | <small>updated on: <%= @team_member.updated_at.strftime("%a, %d %B %Y %H:%M ") %></small></p>
              
              <%= link_to "Back to All Team Members", team_members_path, class: "btn btn-falcon-info btn-sm px-3 " %>
              <div class="border-dashed-bottom my-4 d-lg-none"></div>
            </div>

          </div>
        </div>
      </div>



        <div class="row g-0" id="client-data">

          <div class="card mb-3">
            <div class="card-header bg-light">
              <h5 class="mb-0 text-warning fw-normal">Team Member Information</h5>
            </div>

            <div class="card-body text-justify">
              <div class="flex-1 position-relative ps-2">
                <%= render @team_member %>
              </div>
            </div>
          </div>


          <div class="card mb-3">
            <div class="card-header bg-light d-flex justify-content-between">
              <h5 class="mb-0 text-warning fw-normal">Project Tasks</h5>
            </div>

            <div class="card-body text-justify">
              <div class="flex-1 position-relative ps-2">
              <% @team_member.tasks.each do |task| %>
                <%= render "team_members/task", task: task %>
              <%end%>
                
              </div>
            </div>
          </div>

         
        

        </div>




    </div>
  </div>

</main>