config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'

  get 'dashboard/index'
  get 'activities/index'
  get 'profile/:id', to: 'profile#show', as: :profile

  get 'pricing', to: 'pages#pricing', as: :pricing

  resources :projects do
    resources :tasks do
      member do
        patch 'remove_team_member'
      end
    end

    member do
      get 'team_members'
      get 'reports'
      get 'project_report'
    end
  end

  resources :team_members

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_for :team_members, controllers: {
    sessions: 'project_members/sessions'
  }, path: 'project_members'
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id             :uuid             not null, primary key
#  user_id        :uuid             not null
#  project_name   :text             not null
#  description    :text             not null
#  project_number :text             not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  account_id     :uuid             not null
#
class Project < ApplicationRecord
  acts_as_tenant(:account)
  belongs_to :user

  has_many :tasks

  # validations
  validates :project_name, presence: true
  validates :description, presence: true

  # Public activity tracking
  include PublicActivity::Model
  tracked owner: proc { |controller, _model| controller.current_tenant }

  has_many :activities, as: :trackable, class_name: 'PublicActivity::Activity', dependent: :destroy

  def to_s
    project_name
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  set_current_tenant_through_filter
  before_action :set_current_account
  layout 'dashboard'
  devise_group :project_member, contains: %i[user team_member]

  before_action :authenticate_project_member!

  # before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @pagy, @projects = pagy(Project.order(created_at: :desc), items: 10)
  end

  # GET /projects/1 or /projects/1.json
  def show
    @project = load_project
    @tasks = @project.tasks
  end

  # GET /projects/new
  def new
    @project = Project.new
    # byebug
  end

  # GET /projects/1/edit
  def edit
    load_project
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user
    @project = ProjectUniqueNumber.new.create_project_number(@project)

    respond_to do |format|
      if @project.save

        format.html { redirect_to project_url(@project), notice: 'Project was successfully created.' }

      else
        flash.now[:alert] = 'Project has not been created'
        format.html { render :new, status: :unprocessable_entity }

      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    @project = load_project

    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: 'Project was successfully updated.' }

      else
        flash.now[:alert] = 'Project has not been updated'
        format.html { render :edit, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project = load_project

    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  def reports
    @project = load_project
  end

  def team_members
    @project = load_project
    @tasks = @project.tasks
    @total = []
    @tasks.each do |task|
      @total << task.team_members.pluck(:id)
    end
    @total = @total&.flatten!(-1)&.uniq!&.count
  end

  def project_report
    @project = load_project

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'Ledger Cub Project Report',
               template: 'projects/project_report',
               formats: [:html],
               dispostion: :inline,
               type: 'application/pdf',
               layout: 'project_report_pdf'
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def load_project
    @project = Project.find(params[:id])
  end

  def set_current_account
    return unless current_user.present?

    current_account = current_user.account
    ActsAsTenant.current_tenant = current_account
  end

  # Only allow a list of trusted parameters through.
  def project_params
    params.require(:project).permit(
      :project_name,
      :description,
      :project_number
    )
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/projects/_form.html.erb
<div class="card mb-3">
  <div class="card-header">
    <div class="row flex-between-end">
      <div class="col-auto align-self-center">
        <h5 class="mb-0" data-anchor="data-anchor">Project Details</h5>
      </div>
    </div>
  </div>
  <div class="card-body bg-light">

    <%= form_with(model: project, data: {turbo: false}) do |form| %>
      <% if project.errors.any? %>
        <div style="color: red">
          <h6 class="fw-normal text-700"><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h6>

          <ul>
            <% project.errors.each do |error| %>
              <li><span class="badge bg-danger"><%= error.full_message %></span></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="row gx-2">
        <div class="col-12 mb-3">
          <%= form.label :project_name, class: "form-label" %>
          <%= form.text_field :project_name, class: "form-control" %>
        </div>

        <div class="col-12 mb-3">
          <%= form.label :description, class: "form-label" %>
          <%= form.text_area :description, class: "form-control" %>
        </div>
      </div>

      <div>
        <%= form.submit class: "btn btn-primary" %>
        <% if project.persisted? %>
          <%= link_to "Cancel", project_path(@project), class: "btn btn-secondary me-1"%>
        <%else%>
          <%= link_to "Back to All projects", projects_path, class: "btn btn-secondary me-1" %>
        <%end%>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_list_of_projects.html.erb
<div class="card">
  <div class="card-header">
    <div class="row flex-between-center">
      <div class="col-4 col-sm-auto d-flex align-items-center pe-0">
        <h5 class="fs-0 mb-0 text-nowrap py-2 py-xl-0">Projects</h5>
      </div>
      <div class="col-8 col-sm-auto text-end ps-2">
        <div id="table-customers-replace-element">
        <% if user_signed_in? %>
          <%= link_to new_project_path, class: "btn btn-falcon-default btn-sm" do %>
            <span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span>
            <span class="d-none d-sm-inline-block ms-1">New</span>
          <%end%>
        <%end%>


        </div>
      </div>
    </div>
  </div>
  <div class="card-body bg-light px-1 py-0">
    <div class="row g-0 text-center fs--1">
      <% @projects.each do |project| %>
        <%= render partial: "project_list_preview", locals: {project: project} %>
      <%end%>
    </div>
    
    
  </div>

  <%= render "projects/pagination" %>



 


</div>

app/views/projects/_pagination.html.erb
<% unless @projects.empty? %>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </ul>
</nav>
<%end%>

app/views/projects/_project.html.erb
  <h6 class="fs-0 mb-0">
    <%= @project.project_name %>
    <span data-bs-toggle="tooltip" data-bs-placement="top" title="Verified">
      <small class="fa fa-check-circle text-primary" data-fa-transform="shrink-4 down-2"></small>
    </span>
  </h6>
  <div class="collapse show" id="client-info">
    <p class="mb-0"><%= @project.description %></p>
    <p class="mb-1"><%= @project.project_number %></p>

    <div class="border-dashed-bottom my-3"></div>
    <small class="text-500">Actions</small>
    <div>
      <%= link_to "Edit",edit_project_path(@project),class: "btn btn-primary btn-sm me-1 mb-1", data: { turbo: false } %>
      <%= link_to "Destroy", project_path(@project), class: "btn btn-danger btn-sm me-1 mb-1", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
    </div>
  </div>

app/views/projects/_project_list_preview.html.erb
<% unless project.id == nil %>
  <div class="col-6 col-md-4 col-lg-3 col-xxl-2 mb-1">
    <div class="bg-white dark__bg-1100 p-3 h-100">
      <%= link_to image_tag("project.png", class: "img-thumbnail img-fluid rounded-circle mb-3 shadow-sm", alt: "", width: "100"), project %>
      <h6 class="mb-1">
        <%= link_to project.project_name, project %>
      </h6>
    </div>
  </div>
<%end%>

app/views/projects/edit.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>

      <%= render "layouts/flash" %>
      <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(<%= asset_path "illustrations/corner-4.png" %>);">
        </div>
       

        <div class="card-body position-relative">
          <div class="row">
            <div class="col-lg-8">
              <h3>Edit Project</h3>
            </div>
          </div>
        </div>
      </div>

      <%= render "form", project: @project %>

    

      
    </div>
    
  </div>
</main>

app/views/projects/index.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>

      
      <%= render "layouts/flash" %>
      <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(<%= asset_path "illustrations/corner-4.png" %>);">
        </div>
       

        <div class="card-body position-relative">
          <div class="row">
            <div class="col-lg-8">
            <% if team_member_signed_in? %>
              <h3>Team <%= current_team_member.account.user.first_name %>'s projects</h3>
            <%else%>
              <h3><%= current_user.first_name%>'s projects</h3>
            <%end%>
              <p class="mb-0">List of all projects</p>
            </div>
          </div>
        </div>
      </div>


      <%= render "projects/list_of_projects" %>

     

      
    </div>
    
  </div>

</main>

app/views/projects/new.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>

      <%= render "layouts/flash" %>
      
      <div class="card mb-3">
        <div class="bg-holder d-none d-lg-block bg-card" style="background-image:url(<%= asset_path "illustrations/corner-4.png" %>);">
        </div>
        

        <div class="card-body position-relative">
          <div class="row">
            <div class="col-lg-8">
              <h3>New Project</h3>
            </div>
          </div>
        </div>
      </div>

      <%= render "form", project: @project %>

     

      
    </div>
    
  </div>
</main>

app/views/projects/project_report.html.erb
<div class="card mb-3">


  <div class="card-body position-relative">
    <div class="row">
      <div class="col-lg-8">
        <h1>Project Report</h1>
        <p class="mb-0">Project Report for <%= current_user.full_name %></p>
      </div>
    </div>
  </div>
</div>

<%= image_tag wicked_pdf_asset_base64('ledger_cub_orange.png') %>

app/views/projects/reports.html.erb
<%= turbo_frame_tag "frame_tabs", autoscroll: true, data: { autoscroll_block: "start", autoscroll_behavior: "smooth"}  do %>
  <div class="row g-0" id="client-data">
   
      <div class="card mb-3">
        <div class="card-header bg-light">
          <h5 class="mb-0 text-success fw-normal" id="measurements">Reports</h5>
          
        </div>
      </div>


      <div class="card mb-3">
        <div class="card-header bg-light">
          <h5 class="mb-0">Project Reports</h5>
        </div>
        <div class="card-body text-justify">
          <div class="card bg-light mb-2">
            
          </div>   


        </div>

      </div>

  

      <div class="card mb-3">
        <div class="card-header bg-light">
          <h5 class="mb-0">Reports PDF</h5>
        </div>
        <div class="card-body text-justify">
          <div class="card bg-light mb-2">
            <div class="card-body p-3">
              <p class="fs--1 mb-0">
              <%= link_to project_report_project_path(@project, format: :pdf), target: "_blank" do  %>
                <span class="fas fa-exchange-alt me-2" data-fa-transform="rotate-90">
                </span>
                Create a project report pdf file for archiving 
              <%end%>
            </div>
            
          </div>   


        </div>

      </div>
  
  </div>
<%end%>

app/views/projects/show.html.erb
<main class="main" id="top">
  <div class="container" data-layout="container">
    <%= render "shared/dashboard_sidebar" %>
    <div class="content">
      <%= render "shared/utilities_navigation" %>

      <%= render "layouts/flash" %>

      <div class="card mb-3">
        <div class="card-header bg-progress-gradient position-relative min-vh-25 mb-7">
          

          <div class="avatar avatar-5xl avatar-profile">
            <%= image_tag "project.png", class: "rounded-circle img-thumbnail shadow-sm", width: "200", alt: "" %>
          </div>
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-lg-8">
              <h4 class="mb-1"><%= @project.project_name %>
                <span data-bs-toggle="tooltip" data-bs-placement="right" title="Verified">
                  <small class="fa fa-check-circle text-primary" data-fa-transform="shrink-4 down-2"></small>
                </span>
              </h4>
              <h5 class=" fw-normal">
                <small>created by <%= @project.user.full_name %></span></small>                
              </h5>

              <p class="text-500"><small>created on: <%= @project.created_at.strftime("%a, %d %B %Y %H:%M ") %></small> | <small>updated on: <%= @project.updated_at.strftime("%a, %d %B %Y %H:%M ") %></small></p>
              
              <%= link_to "Back to All Projects", projects_path, class: "btn btn-falcon-info btn-sm px-3 " %>
              <div class="border-dashed-bottom my-4 d-lg-none"></div>
            </div>

          </div>
        </div>
      </div>

      <div class="row g-3 mb-3">
        <div class="col-sm-6 col-md-4">
          <div class="card overflow-hidden" style="min-width: 12rem">
            <div class="bg-holder bg-card" style="background-image:url(<%= asset_path "illustrations/corner-1.png" %>);">
            </div>
            

            <div class="card-body position-relative">
              <h6>
                <%= @project.project_name %>'s
              </h6>
              <div class="display-4 fs-1 mb-2 fw-normal font-sans-serif text-warning" data-countup='{"endValue":58.386,"decimalPlaces":2,"suffix":"k"}'>
              <%= link_to "Project Data", 
                project_path(@project),
                class: "text-warning",
                data: { turbo_frame: "frame_tabs"}       
              %>

              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4">
          <div class="card overflow-hidden" style="min-width: 12rem">
            <div class="bg-holder bg-card" style="background-image:url(<%= asset_path "illustrations/corner-3.png" %>);">
            </div>
            <!--/.bg-holder-->

            <div class="card-body position-relative">
              <h6>
              <%= @project.project_name %>'s </h6>
              
              
              <div class="display-4 fs-1 mb-2 fw-normal font-sans-serif text-info" data-countup='{"endValue":23.434,"decimalPlaces":2,"suffix":"k"}'>
                <%= link_to "Team Members", 
                    team_members_project_path(@project), 
                    class: "text-info",
                    data: { turbo_frame: "frame_tabs"}
                      %>
              </div>
              
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4">
          <div class="card overflow-hidden" style="min-width: 12rem">
            <div class="bg-holder bg-card" style="background-image:url(<%= asset_path "illustrations/corner-3.png" %>);">
            </div>
            <!--/.bg-holder-->

            <div class="card-body position-relative">
              <h6>
                <%= @project.project_name%>'s
              </h6>
              <div class="display-4 fs-1 mb-2 fw-normal font-sans-serif">
                <%= link_to "Reports", 
                    reports_project_path(@project), 
                    class: "text-success",
                    data: { turbo_frame: "frame_tabs"}
                      %>
              </div>
            </div>
          </div>
        </div>
      </div>


      <%= turbo_frame_tag "frame_tabs", autoscroll: true, data: { autoscroll_block: "start", autoscroll_behavior: "smooth"} do %>
        <div class="row g-0" id="client-data">

          <div class="card mb-3">
            <div class="card-header bg-light">
              <h5 class="mb-0 text-warning fw-normal">Project Information</h5>
            </div>

            <div class="card-body text-justify">
              <div class="flex-1 position-relative ps-2">
                <%= render @project %>
              </div>
            </div>
          </div>


          <div class="card mb-3">
            <div class="card-header bg-light d-flex justify-content-between">
              <h5 class="mb-0 text-warning fw-normal">Project Tasks</h5>
              <% if user_signed_in? %>
                <%= link_to new_project_task_path(@project), class: "btn btn-falcon-default btn-sm", data: {turbo: false } do %>
                  <span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span>
                  <span class="d-none d-sm-inline-block ms-1">New Project Task</span>
                <%end%>
              <%end%>
            </div>

            <div class="card-body text-justify">
              <div class="flex-1 position-relative ps-2">
              <% @tasks.each do |task| %>
                <%= render task %>
              <%end%>
                
              </div>
            </div>
          </div>

         
        

        </div>
      <%end%>



    </div>
  </div>

</main>

app/views/projects/team_members.html.erb
<%= turbo_frame_tag "frame_tabs", autoscroll: true, data: { autoscroll_block: "start", autoscroll_behavior: "smooth"}  do %>
  <div class="row g-0" id="client-data">  
    <div class="card mb-3">
      <div class="card-header bg-light">
        <h5 class="mb-0 text-info fw-normal" id="measurements">List of team members for <%= @project.project_name %></h5>
        
      </div>
    </div>


    <div class="card mb-3">
      <div class="card-body">
        <div class="table-responsive fs--1">
          <table class="table table-striped border-bottom">
            <thead class="bg-200 text-900">
              <tr>
                <th class="border-0">Team Member</th>
                <th class="border-0 text-center">Task</th>
                <th class="border-0 text-end">Task Status</th>
                <th class="border-0 text-end">Task Start Date</th>
                <th class="border-0 text-end">Task End Date</th>
              </tr>
            </thead>
            <tbody>
            <% @tasks.each do |task| %>
              <% task.team_members.each do |team_member| %>
                <tr class="border-200">
                  <td class="align-middle">
                    <h6 class="mb-0 text-nowrap"><%= team_member.full_name %></h6>
                    <p class="mb-0">Role</p>
                  </td>
                  <td class="align-middle text-center"><%= task.name %></td>
                  <td class="align-middle text-end"><span class="badge badge-soft-info"><%= task.status %></span></td>
                  <td class="align-middle text-end"><%= task.start_date.strftime("%d %b %Y at %H:%M %p") %></td>
                  <td class="align-middle text-end"><%= task.end_date.strftime("%d %b %Y at %H:%M %p") %></td>
                </tr>
              <%end%>
            <%end%>
 
            </tbody>
          </table>
        </div>
        <div class="row g-0 justify-content-end">
          <div class="col-auto">
            <table class="table table-sm table-borderless fs--1 text-end">
              <tr>
                <th class="text-900">Total Tasks</th>
                <td class="fw-semi-bold"><%= @tasks.count %></td>
              </tr>
              <tr class="border-top">
                <th class="text-900">Total Team Members on this project</th>
                <td class="fw-semi-bold"><%= @total %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
<%end%>