config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'

  get 'dashboard/index'
  get 'activities/index'
  get 'profile/:id', to: 'profile#show', as: :profile

  get 'pricing', to: 'pages#pricing', as: :pricing

  resources :projects do
    resources :tasks do
      member do
        patch 'remove_team_member'
      end
    end

    member do
      get 'team_members'
      get 'reports'
      get 'project_report'
    end
  end

  resources :team_members

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_for :team_members, controllers: {
    sessions: 'project_members/sessions'
  }, path: 'project_members'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  set_current_tenant_through_filter
  before_action :set_current_account
  layout 'dashboard'
  devise_group :project_member, contains: %i[user team_member]

  before_action :authenticate_project_member!

  def index
    total_projects_by_month = Project.group_by_month_of_year(:created_at).count

    @month_names = []

    total_projects_by_month.each_key do |key|
      @month_names << Date::MONTHNAMES[key]
    end

    @monthly_project_total = total_projects_by_month.values
  end

  private

  def set_current_account
    return unless current_user.present?

    current_account = current_user.account
    ActsAsTenant.current_tenant = current_account
  end
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/views/shared/dashboard/_dashboard_main.html.erb
<li class="nav-item ">
 
  
  <%= link_to dashboard_index_path, class: "nav-link active", data: { role: "button" } do %>
    <div class="d-flex align-items-center">
      <span class="nav-link-icon">
        <span class="fas fa-chart-pie">
        </span>
      </span>
      <span class="nav-link-text ps-1">Dashboard</span>
    </div>
  <%end%>
  
</li>

app/views/shared/dashboard/_main_application_navigation.html.erb
<li class="nav-item">
  <!-- label-->
  <div class="row navbar-vertical-label-wrapper mt-3 mb-2">
    <div class="col-auto navbar-vertical-label">
      LedgerCub
    </div>
    <div class="col ps-0">
      <hr class="mb-0 navbar-vertical-divider" />
    </div>
  </div>
  <!-- parent pages-->
  <a class="nav-link dropdown-indicator" 
      href="#clinic" 
      role="button" 
      data-bs-toggle="collapse" 
      aria-expanded="false" 
      aria-controls="clinic">         
    <div class="d-flex align-items-center">
      <span class="nav-link-icon">
        <span class="fas fa-clinic-medical"></span>
      </span>
      <span class="nav-link-text ps-1">Projects</span>
    </div>
  </a>
  <ul class="nav collapse" id="clinic">
    <li class="nav-item">
      
      <%= link_to projects_path ,class: "nav-link", data: { aria_expanded: "false", data_bs_toggle: ""} do %>
        <div class="d-flex align-items-center">
          <span class="nav-link-text ps-1">Projects</span>
        </div>
      <%end%>
      
      <!-- more inner pages-->
    </li>
  </ul>
  <a class="nav-link dropdown-indicator" 
      href="#food" 
      role="button" 
      data-bs-toggle="collapse" 
      aria-expanded="false" 
      aria-controls="food">
    <div class="d-flex align-items-center">
      <span class="nav-link-icon">
        <span class="fas fa-apple-alt"></span>
      </span>
      <span class="nav-link-text ps-1">Teams</span>
    </div>
  </a>
  <ul class="nav collapse" id="food">
    <li class="nav-item">
      
      <%= link_to team_members_path, class: "nav-link", data: { data_bs_toggle: "", aria_expanded: "false" } do %>
        <div class="d-flex align-items-center">
          <span class="nav-link-text ps-1">Team Members</span>
        </div>
      <%end%>
      
      <!-- more inner pages-->
    </li>
  </ul>

</li>

app/views/shared/dashboard/_mobile_navigation_logo.html.erb
<button 
  class="btn navbar-toggler-humburger-icon navbar-toggler me-1 me-sm-3" 
  type="button" 
  data-bs-toggle="collapse" 
  data-bs-target="#navbarVerticalCollapse" 
  aria-controls="navbarVerticalCollapse" 
  aria-expanded="false" 
  aria-label="Toggle Navigation">
    <span class="navbar-toggle-icon">
      <span class="toggle-line"></span>
    </span>
</button>

<%= link_to dashboard_index_path, class: "navbar-brand me-1 me-sm-3" do %>
  <div class="d-flex align-items-center">
    <%= image_tag "ledger_cub_blue.png" ,class: "me-2", alt: "" %>
  </div>
<%end%>

app/views/shared/dashboard/_sidebar_navigation_logo.html.erb
<div class="d-flex align-items-center">
  <%= link_to dashboard_index_path ,class: "navbar-brand" do %>
    <div class="d-flex align-items-center py-3">
    <%= image_tag "ledger_cub_blue.png", class: "me-2" ,alt: "" %>
    </div>
  <%end%>
</div>

app/views/shared/dashboard/_statistics_navigation.html.erb
<li class="nav-item">
  <!-- label-->
  <div class="row navbar-vertical-label-wrapper mt-3 mb-2">
    <div class="col-auto navbar-vertical-label">Statistics
    </div>
    <div class="col ps-0">
      <hr class="mb-0 navbar-vertical-divider" />
    </div>
  </div>
  <!-- parent pages-->
  
  <%= link_to reports_index_path, class: "nav-link", data: { role: "button", data_bs_toggle: "", aria_expanded: "false" } do %>
    <div class="d-flex align-items-center">
      <span class="nav-link-icon">
        <span class="fas fa-chart-bar"></span>
      </span>
      <span class="nav-link-text ps-1">Reports</span>
    </div>
  <%end%>
</li>

app/views/shared/dashboard/_user_profile_navigation.html.erb
<ul class="navbar-nav navbar-nav-icons ms-auto flex-row align-items-center">

  <li class="nav-item">
    <div class="ps-2">
    <% if user_signed_in? %>
      <%= current_user.first_name %>&nbsp;<%= current_user.last_name %>
    <% elsif team_member_signed_in? %>
      <%= current_team_member.first_name %>&nbsp;<%= current_team_member.last_name %>
    <%end%>
    
      
    </div>
  </li>
  <li class="nav-item dropdown">
    <a class="nav-link pe-0 ps-2" 
        id="navbarDropdownUser" 
        role="button" 
        data-bs-toggle="dropdown" 
        aria-haspopup="true" 
        aria-expanded="false">
      <div class="avatar avatar-xl">
        <%= image_tag "illustrations/system_user.png", class: "rounded-circle" %>
      </div>
    </a>
    <div class="dropdown-menu dropdown-menu-end py-0" aria-labelledby="navbarDropdownUser">
      <div class="bg-white dark__bg-1000 rounded-2 py-2">
        
        <%= link_to "#", class: "dropdown-item fw-bold text-warning" do %>
          <span class="fas fa-crown me-1"></span>
          <span>Manage Subscription</span>
        <%end%>

        <div class="dropdown-divider"></div>
        <% if user_signed_in? %>
          <%= link_to "Your profile", profile_path(current_user), class: "dropdown-item" %>
        <%elsif team_member_signed_in? %>
          <%= link_to "Your profile", profile_path(current_team_member),class: "dropdown-item" %>
        <%end%>

        <% if user_signed_in? %>
          <%= link_to "Activity History", activities_index_path, class: "dropdown-item" %>
        <%end%>
        <!-- <a class="dropdown-item" href="#!">Notifications</a> -->

        <div class="dropdown-divider"></div>
        

        
        <% if user_signed_in? %>
          <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item", data: {turbo: false} %>
        <%elsif team_member_signed_in? %>
          <%= button_to "Log Out", destroy_team_member_session_path, method: :delete, class: "dropdown-item", data: {turbo: false} %>
        <%end%>
      </div>
    </div>
  </li>



</ul>